package es.wokis.localization

object LocalizationKeys {
    const val PLAY_COMMAND_DESCRIPTION = "play_command_description"
    const val PLAY_COMMAND_INPUT_DESCRIPTION = "play_command_input_description"
    const val UNKNOWN_COMMAND = "unknown_command"
    const val NOW_PLAYING = "now_playing"
    const val NO_MATCHES = "no_matches"
    const val ADDED_TRACK_TO_QUEUE = "added_track_to_queue"
    const val ADDED_SONGS_TO_QUEUE = "added_songs_to_queue"
    const val FOUND_TRACK_LIST = "found_track_list"
    const val LOAD_FAILED = "load_failed"
    const val MESSAGE_PROCESSOR_INVALID_LINK = "message_processor_invalid_link"
    const val FIXED_UP_LINK = "fixed_up_link"
    const val ERROR_NO_VOICE_CHANNEL = "error_no_voice_channel"
    const val ERROR_NO_TEXT_CHANNEL = "error_no_text_channel"
    const val ERROR_NO_GUILD = "error_no_guild"
    const val ERROR_NO_CONTENT_PROVIDED = "error_no_content_provided"
    const val SEARCHING_SONG = "searching_song"
    const val QUEUE_COMMAND_DESCRIPTION = "queue_command_description"
    const val QUEUE_EMBED_TITLE = "queue_embed_title"
    const val QUEUE_EMBED_DESCRIPTION = "queue_embed_description"
    const val QUEUE_EMBED_FOOTER = "queue_embed_footer"
    const val QUEUE_PREVIOUS_BUTTON_LABEL = "queue_previous_button_label"
    const val QUEUE_NEXT_BUTTON_LABEL = "queue_next_button_label"
    const val SKIP_COMMAND_DESCRIPTION = "skip_command_description"
    const val SKIP_COMMAND_RESPONSE = "skip_command_response"
    const val SHUFFLE_COMMAND_DESCRIPTION = "shuffle_command_description"
    const val SHUFFLE_COMMAND_RESPONSE = "shuffle_command_response"
    const val TTS_COMMAND_DESCRIPTION = "tts_command_description"
    const val TTS_COMMAND_INPUT_DESCRIPTION = "tts_command_input_description"
    const val TTS_COMMAND_RESPONSE = "tts_command_response"
}
